### ISSUE TITLE
Questions about your dataset

### ISSUE THREAD

**Issue by zhaoxu-zhang** [ZhangShurong/rebucket#1]
Hi! I have a question about how you obtain your dataset! Did you get the description of the bugs from the website then apply algorithm from "Extracting Structural Information from Bug Reports" to extract the stacktrace from it ?
Wish for your reply!

**Comment by ZhangShurong** [comment]
My dataset is  https://github.com/logpai/bugrepo. You can find some details there.
and the code for extracting stack trace is from https://github.com/wintere/Flick.

**Comment by ZhangShurong** [comment]
@DennielZhang 我看到你是南方科技大学的。我记得我们最近在你们学校举办相关的比赛。我建议你们还是采用新的算法和数据集比较好。

**Comment by zhaoxu-zhang** [comment]
感谢您的回复与意见！我们会采用最新的算法的！

**Comment by ZhangShurong** [comment]
我把这个issue打开了。估计还会有人看到的。

**Comment by zhaoxu-zhang** [comment]
好的！
