### ISSUE TITLE
Java版本

### ISSUE THREAD

**Issue by Joy-Panda** [ZhangShurong/rebucket#3]
有没有java版本的？

**Comment by ZhangShurong** [comment]
没有耶。不过函数比较简单，可以参考c++的。

**Comment by Joy-Panda** [comment]
rebucket.py这个是python的实现吗？

**Comment by Joy-Panda** [comment]
rebucket.py这个是python的实现吗？

**Comment by Joy-Panda** [comment]
> 没有耶。不过函数比较简单，可以参考c++的。

rebucket.py这个是python的实现吗？

**Comment by ZhangShurong** [comment]
> > 没有耶。不过函数比较简单，可以参考c++的。
> 
> rebucket.py这个是python的实现吗？

是的，主要是get_dist方法。

**Comment by Joy-Panda** [comment]
> > > 没有耶。不过函数比较简单，可以参考c++的。
> > 
> > 
> > rebucket.py这个是python的实现吗？
> 
> 是的，主要是get_dist方法。

好的，3Q
