### ISSUE TITLE
对于算法实现的疑问

### ISSUE THREAD

**Issue by TedaLIEz** [ZhangShurong/rebucket#4]
你好，我看到在你的实现中 https://github.com/ZhangShurong/rebucket/blob/1b11a1cb35175df0baecfe195350df4ef6a63865/rebucket/src/rebucket.cpp?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L37 ，当len(frame1) or len(frame2) == 1时，直接返回sim=1，请问这个是什么原因呢？我翻阅了对应的论文，里面似乎并没有提到这个特殊的逻辑

**Comment by ZhangShurong** [comment]
确实没有这个逻辑，长度为1的堆栈没有意义，所以我直接返回了1.
